# Generated by Django 6.0.1 on 2026-02-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_studentexam_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='ipfs_cid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
