# Generated by Django 6.0.1 on 2026-02-04 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_questionpaper_question_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='uploaded_by',
            field=models.ForeignKey(limit_choices_to={'role': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
