# Generated by Django 6.0.1 on 2026-02-13 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_alter_questionpaper_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'STAFF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exams', to=settings.AUTH_USER_MODEL),
        ),
    ]
