# Generated by Django 6.0.1 on 2026-02-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_exam_assigned_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='status',
        ),
        migrations.AddField(
            model_name='exam',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted For Approval'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked')], default='DRAFT', max_length=20),
        ),
    ]
