# Generated by Django 6.0.1 on 2026-02-15 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_remove_exam_status_exam_workflow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted For Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='question_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attempts', to='exam.exam'),
        ),
    ]
