# Generated by Django 6.0.1 on 2026-03-02 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_exam_workflow_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='enrolled_exams', to=settings.AUTH_USER_MODEL),
        ),
    ]
