# Generated by Django 6.0.1 on 2026-03-02 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_studentexam_enrolled_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexam',
            name='enrolled_students',
        ),
        migrations.AddField(
            model_name='exam',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='enrolled_exams', to=settings.AUTH_USER_MODEL),
        ),
    ]
