# Generated by Django 6.0.1 on 2026-03-02 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_remove_studentexam_enrolled_students_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE_EXAM', 'Create Exam'), ('APPROVE_EXAM', 'Approve Exam'), ('LOCK_PAPER', 'Lock Question Paper'), ('ENROLL_STUDENT', 'Enroll Student'), ('SUBMIT_EXAM', 'Submit Exam'), ('COMMIT_RESULT', 'Commit Result')], max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
