# Generated by Django 6.0.1 on 2026-03-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='total_questions_allowed',
            field=models.IntegerField(default=10),
        ),
    ]
