# Generated by Django 6.0.1 on 2026-03-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_exam_total_questions_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('CREATE_EXAM', 'Create Exam'), ('APPROVE_EXAM', 'Approve Exam'), ('LOCK_PAPER', 'Lock Question Paper'), ('ENROLL_STUDENT', 'Enroll Student'), ('SUBMIT_EXAM', 'Submit Exam'), ('COMMIT_RESULT', 'Commit Result'), ('ADD_QUESTION', 'Add Question')], max_length=50),
        ),
    ]
