# Generated by Django 6.0.1 on 2026-03-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
