# Generated by Django 6.0.1 on 2026-03-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('ECE', 'Electronics'), ('MECH', 'Mechanical'), ('CIVIL', 'Civil'), ('MBA', 'MBA'), ('ALL', 'All Departments')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='semester',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
