# Generated by Django 6.0.1 on 2026-03-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_exam_department_exam_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
